//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DNSSECValidator.rc
//
#define IDS_PROJNAME                    100
#define IDR_DNSSECVALIDATOR             101
#define IDS_DNSSEC_CONNECTION_DOMAIN_SECURED 101
#define IDR_DNSSECVALIDATORBHO          102
#define IDS_DNSSEC_CONNECTION_DOMAIN_INVIPADDR_SECURED 102
#define IDS_DNSSEC_CONNECTION_NODOMAIN_SECURED 103
#define IDR_MENU_POPUP                  104
#define IDS_DNSSEC_CONNECTION_NODOMAIN_INVIPADDR_SECURED 104
#define IDS_DNSSEC_CONNECTION_INVSIGDOMAIN_SECURED 105
#define IDS_DNSSEC_CONNECTION_INVSIGDOMAIN_INVIPADDR_SECURED 106
#define IDS_DNSSEC_DOMAIN_SIGNATURE_VALID 107
#define IDS_DNSSEC_AUTH_DOMAIN_SIGNATURE_VALID 108
#define IDS_DNSSEC_INVIPADDR_DOMAIN_SIGNATURE_VALID 109
#define IDS_DNSSEC_DOMAIN_SIGNATURE_INVALID 110
#define IDS_DNSSEC_INVIPADDR_DOMAIN_SIGNATURE_INVALID 111
#define IDS_DNSSEC_NODOMAIN_SIGNATURE_VALID 112
#define IDS_DNSSEC_AUTH_NODOMAIN_SIGNATURE_VALID 113
#define IDS_DNSSEC_INVIPADDR_NODOMAIN_SIGNATURE_VALID 114
#define IDS_DNSSEC_NODOMAIN_SIGNATURE_INVALID 115
#define IDS_DNSSEC_INVIPADDR_NODOMAIN_SIGNATURE_INVALID 116
#define IDS_DNSSEC_DOMAIN_UNSECURED     117
#define IDS_DNSSEC_NODOMAIN_UNSECURED   118
#define IDS_DNSSEC_TOOLTIP_SECURED      119
#define IDS_DNSSEC_TOOLTIP_UNSECURED    120
#define IDS_DNSSEC_TOOLTIP_ACTION       121
#define IDS_DNSSEC_TOOLTIP_ERROR        122
#define IDS_DNSSEC_SECURED_LABEL        123
#define IDS_DNSSEC_UNSECURED_LABEL      124
#define IDS_DNSSEC_THISDOMAIN_LABEL     125
#define IDS_DNSSEC_THISNODOMAIN_LABEL   126
#define IDS_DNSSEC_THISSECUREDDOMAIN_LABEL 127
#define IDS_DNSSEC_THISUNSECUREDDOMAIN_LABEL 128
#define IDS_NONE                        129
#define IDS_ADDON_INIT                  130
#define IDS_DNSSEC_ERROR_LABEL          131
#define IDI_ICON_KEY_GREEN              206
#define IDI_ICON_KEY_ACTION             208
#define IDI_ICON_KEY_GREY               210
#define IDI_ICON_KEY_GREY_RC            211
#define IDI_ICON_KEY_ORANGE             212
#define IDI_ICON_KEY_RED                213
#define IDI_ICON_KEY_GREY_YT            214
#define ID_POPUP_RESOLVERSETTING        32768
#define ID_RESOLVERSETTING_CZ           32769
#define ID_ENABLED                      32770
#define ID_ABOUT                        32771
#define ID_RESOLVER_OARC                32772
#define ID_RESOLVER_CZNIC               32773
#define ID_RESOLVER_SYSTEM              32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
