//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by kbbar.rc
//
#define IDS_PROJNAME                    100
#define IDS_TOOLBARNAME                 1046
#define IDR_KBBARBAND			        1045
#define ID_BUTTON1                      32768
#define ID_BUTTON2	                    32769
#define IDI_ICON_KEY_ACTION1            300
#define IDI_ICON_KEY_GREEN1             301
#define IDI_ICON_KEY_RED1               302
#define IDI_ICON_KEY_ORANGE1            303
#define IDI_ICON_KEY_GREY1              304
#define IDI_ICON_KEY_GREY_RC1           305
#define IDI_ICON_KEY_GREY_YT1           306
#define IDI_ICON_KEY_GREEN              220
#define IDI_ICON_KEY_ACTION             221
#define IDI_ICON_KEY_GREY               222
#define IDI_ICON_KEY_GREY_RC            223
#define IDI_ICON_KEY_ORANGE             224
#define IDI_ICON_KEY_RED                225
#define IDI_ICON_KEY_GREY_YT            226
#define IDR_MENU_POPUP		            1000
#define IDS_DNSSEC_CONNECTION_DOMAIN_SECURED 101
#define IDS_DNSSEC_CONNECTION_DOMAIN_INVIPADDR_SECURED 102
#define IDS_DNSSEC_CONNECTION_NODOMAIN_SECURED 103
#define IDS_DNSSEC_CONNECTION_NODOMAIN_INVIPADDR_SECURED 104
#define IDS_DNSSEC_CONNECTION_INVSIGDOMAIN_SECURED 105
#define IDS_DNSSEC_CONNECTION_INVSIGDOMAIN_INVIPADDR_SECURED 106
#define IDS_DNSSEC_DOMAIN_SIGNATURE_VALID 107
#define IDS_DNSSEC_AUTH_DOMAIN_SIGNATURE_VALID 108
#define IDS_DNSSEC_INVIPADDR_DOMAIN_SIGNATURE_VALID 109
#define IDS_DNSSEC_DOMAIN_SIGNATURE_INVALID 110
#define IDS_DNSSEC_INVIPADDR_DOMAIN_SIGNATURE_INVALID 111
#define IDS_DNSSEC_NODOMAIN_SIGNATURE_VALID 112
#define IDS_DNSSEC_AUTH_NODOMAIN_SIGNATURE_VALID 113
#define IDS_DNSSEC_INVIPADDR_NODOMAIN_SIGNATURE_VALID 114
#define IDS_DNSSEC_NODOMAIN_SIGNATURE_INVALID 115
#define IDS_DNSSEC_INVIPADDR_NODOMAIN_SIGNATURE_INVALID 116
#define IDS_DNSSEC_DOMAIN_UNSECURED     117
#define IDS_DNSSEC_NODOMAIN_UNSECURED   118
#define IDS_DNSSEC_TOOLTIP_SECURED      119
#define IDS_DNSSEC_TOOLTIP_UNSECURED    120
#define IDS_DNSSEC_TOOLTIP_ACTION       121
#define IDS_DNSSEC_TOOLTIP_ERROR        122
#define IDS_DNSSEC_SECURED_LABEL        123
#define IDS_DNSSEC_UNSECURED_LABEL      124
#define IDS_DNSSEC_THISDOMAIN_LABEL     125
#define IDS_DNSSEC_THISNODOMAIN_LABEL   126
#define IDS_DNSSEC_THISSECUREDDOMAIN_LABEL 127
#define IDS_DNSSEC_THISUNSECUREDDOMAIN_LABEL 128
#define IDS_NONE                        129
#define IDS_ADDON_INIT                  130
#define IDS_DNSSEC_ERROR_LABEL          131
#define IDS_ADDON_INIT                  130
#define ID_MENUPOPUP_OPTION1            32773
#define ID_MENUPOPUP_OPTION2            32772
#define ID_MORE_LINK1                   32778
#define ID_MORE_LINK2                   32779
#define ID_ENABLED                      32770
#define ID_ABOUT                        32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           144
#endif
#endif
